# Generated by Django 5.0.1 on 2024-03-26 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('royaldrive', '0012_order_orderitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='order_object',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='basket_item_object',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItems',
        ),
    ]
