# Generated by Django 5.0.1 on 2024-03-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royaldrive', '0014_order_orderitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouriteitem',
            name='is_item_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('booked', 'booked'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='booked', max_length=200),
        ),
    ]
